Repository getindata/terraform-snowflake-user, pull requests merged in 2023-01, with the labels that each got.

#3 fix: Readme
  README.md
Labels: release/fix

#4 fix: Fix4
  README.md
Labels: release/fix

#6 fix: Labels
  examples/complete/README.md
Labels: release/patch

#7 fix: Remove name from the label module
  main.tf
Labels: release/patch

#8 feat: Add must_change_password variable and credentials outputs
  README.md
  examples/complete/.envrc
  examples/complete/outputs.tf
  main.tf
  outputs.tf
  variables.tf
Labels: release/minor
